# Generated by Django 3.1 on 2021-06-23 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='time',
            field=models.IntegerField(),
        ),
    ]
