# Generated by Django 3.1 on 2021-06-23 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0005_auto_20210623_0059'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='is_finished',
            field=models.BooleanField(default=True),
        ),
    ]
