# Generated by Django 3.1 on 2021-06-23 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0006_interview_is_finished'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
    ]
